name: Build & Release Go

on:
  release:
    types: [published]

jobs:
  update:
    uses: codeshelldev/gh-actions/.github/workflows/go-releaser.yml@main
    name: Go Releaser
    with:
      platforms: linux/amd64, linux/arm64, darwin/amd64, windows/amd64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm:
    name: Release to npm
    needs: update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: go-binaries
          path: dist

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org

      - name: Publish npm package
        run: |
          cp -r dist/* npm/bin/
          cp README.md npm/
          cp LICENSE npm/
          cd npm/
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          npm publish --access public
