name: Build & Release Go

on:
  release:
    types: [published]

jobs:
  update:
    uses: codeshelldev/gh-actions/.github/workflows/go-releaser.yml@main
    name: Go Releaser
    with:
      platforms: linux/amd64, linux/arm64, darwin/amd64, windows/amd64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm:
    name: Release to npm
    needs: update
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: https://npm.pkg.github.com
          scope: "@${{ github.repository_owner }}"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: go-binaries
          path: dist

      - name: Publish npm package
        run: |
          cp -r dist/* npm/bin/
          cp README.md npm/
          cp LICENSE npm/
          cd npm/
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
